store_path: /work/playground2/repo

su_db_username: aiidauser
# su_db_password:  # not yet supported

db_engine: postgresql_psycopg2
db_backend: django

db_host: localhost
db_port: 5432
db_name: aiida
db_username: aiidauser
db_password: verdi

profile: "{{ name }}"
email: aiida@localhost
first_name: MaX
last_name: Scientist
institution: Renkulab

non_interactive: true
